receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
          allowed_headers: ["*"]

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1


processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]
      processors: [batch]
